AuthType=auth/munge
DbdAddr=headnode
DbdHost=headnode
SlurmUser=slurm
DebugLevel=4
LogFile=/var/log/slurm/slurmdbd.log
PidFile=/var/run/slurmdbd.pid
StorageType=accounting_storage/mysql
StoragePass=I7DCgNNl-2ipOqxZEZSWrGd6p
StorageUser=slurm
StorageLoc=slurm_acct_db
